### ISSUE TITLE
New command line option: Only print test Name and Information if there's a failure

### ISSUE THREAD

**Issue by Mike430** [dangmoody/Temper#12]
Something I think would benefit those working within the terminal is an option to only print anything at all if and only if a check fails. At that point, print the information about the test. If we are to do this it would also be a good idea to look at doing text output suppression so you don't get any of the noise of the program running. Just a concise list of failing tests & accompanying errors.

**Comment by dangmoody** [comment]
I'm not sure I'm 100% behind the idea of not printing anything unless a test fails.  If you run a program from the command line it's possible for it to crash without showing anything in the command line.

I will say, tbf, that you could get that functionality already just by overriding `TEMPERDEV__ON_AFTER_TEST`, though obviously that's not as nice as, say, setting a command line flag.

As for supressing command line output of the program you're testing: Yeah, sounds good.  I can see potentially running into issues with trying to supress text output if the program has logging implemented weirdly or something, but I suppose I can take a look at that in the initial exploration.

While writing this, looking back through the code, I realise we never log things like failed tests or other errors to `stderr`, which we probably want to do.  Making an issue for that now...

**Comment by Mike430** [comment]
Just had another chat about it - we'll opt to try and fully surpress all stdout console output to eliminate all application and temper noise and only print any temper checks that fail as well as the test names once concluded before returning the final test results.

**Comment by dangmoody** [comment]
This is done in a branch.  Will close pending a PR and merge.
