### ISSUE TITLE
Add support for ARM

### ISSUE THREAD

**Issue by dangmoody** [dangmoody/Temper#16]
Was reading the README again and saw that we had listed as WIP but there was no issue made for it, so I'm making one now before I forget (again).

**Comment by Mike430** [comment]
Time to break out the Raspberry Pis :)

**Comment by Mike430** [comment]
Still pursuing

**Comment by dangmoody** [comment]
We now support Raspberry Pi (64 bit only).  I imagine this means we also support the MacOS M-series chips but I've not been able to test that yet.

Closing this for now anyway seeing as how I _know_ we can support ARM64 ISA now.
