### ISSUE TITLE
Need separate CHECK functions for comparing doubles as well as floats

### ISSUE THREAD

**Issue by dangmoody** [dangmoody/Temper#17]
As found by @Mike430, if you want to compare `double`s you have to pass it into `TEMPER_CHECK_FLOAT_EQUALS`, which is not ideal for obvious reasons.  Oops!

So we need CHECK functions for doubles too, to reduce friction and make life easier.

The only problem with that is we have `TEMPER_CHECK_ALMOST_EQUALS`, which is ambiguous.  So we need to find a new name for that so we can differentiate between `float` and `double`.

If anyone has any ideas I'm all ears!

**Comment by Mike430** [comment]
So just to give a concrete test case we can fall back on: Temper in it's current form will not compile given this test:

`C
TEMPER_TEST( FloatChecks_ProvidedWithDoubles_CausesNoCompilerErrorsForConversionLoss, TEMPER_FLAG_SHOULD_RUN ) {
    const double lhs = 3.1415926535897931f;
    const double rhs = lhs;
    const double epsilon = 0.5f;
    TEMPER_CHECK_FLOAT_EQUAL( lhs, rhs );
    TEMPER_CHECK_ALMOST_EQUAL( lhs, rhs, epsilon );
    TEMPER_CHECK_NOT_ALMOST_EQUAL( lhs, 4.0f, epsilon );
}
`

After discussing it some more in a call the ideal to do the follow:
`C
Go from:
TEMPER_CHECK_FLOAT_EQUAL // No epsilon provided
TEMPER_CHECK_ALMOST_EQUAL // We require an epsilon
//to:
TEMPER_CHECK_FLOAT_EQUAL // No epsilon provided
TEMPER_CHECK_DOUBLE_EQUAL // No epsilon provided
// With NOT variations
`
The idea here is to take what Christer Ericson talked about here (https://realtimecollisiondetection.net/blog/?p=89) and calculate the perfect epsilon value such that no programmer ever has to provide one again while we keep our API the same size.

So, more Functionality for the same amount of API sounds nice, but this being said, I know for a fact (especially when working with deltatime tests or targeting tests in gameplay code) that sometimes you do need an abnormally high epsilon (whole numbers and up). In this situation I would strongly suggest that we also have:

`C
TEMPER_CHECK_FLOAT_EQUAL_MODIFIER
TEMPER_CHECK_DOUBLE_EQUAL_MODIFIER
`

Where the user gets to say: "Hey, this base, pre-calculated epsilon value from within temper for these numbers add this to it". Failing that we could just keep the ALMOST_EQUAL strategy and provide one where you specify your own whole cloth epsilon for your use case:
`C
TEMPER_CHECK_FLOAT_EQUAL // No epsilon provided
TEMPER_CHECK_FLOAT_EQUAL_EPSILON // We require an epsilon
TEMPER_CHECK_DOUBLE_EQUAL // No epsilon provided
TEMPER_CHECK_DOUBLE_EQUAL_EPSILON // We require an epsilon
// With NOT variations
`

One final alternative would be to have a TEMPER_CHECK function that checks to see if a value falls within a range, so the user specifies an upper and lower boundary. This would achieve the exact same thing but just come at the problem from another angle.

**Comment by Mike430** [comment]
Issue resolved in [e0df55e] - you can now compare doubles. Just need to get the build pipeline working again and polish up our API and we're good.
